In [2]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

sum = a + b

print("Sum =", sum)

Enter first number:  2
Enter second number:  3


Sum = 5


In [7]:
import numpy as np

In [ ]:
np.

In [8]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [10]:
a = np.ones(4)
print(a)

[1. 1. 1. 1.]


In [11]:
a = np.sort([2,3,5,5,6,1])
print(a)

[1 2 3 5 5 6]


In [12]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [13]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64
